version: '3.1'

services:
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    image: espirado/slurm.controller:23.02
    container_name: controller
    privileged: true
    volumes:
      - ./home:/home
      - ./secret:/.secret
    restart: always
    hostname: controller.local.dev
    networks:
      - slurm
    ports:
      - 8787:8787
    environment:
      USE_SLURMDBD: 'true'
      CLUSTER_NAME: snowflake
      SLURMCTLD_PORT: 6817
      SLURMD_PORT: 6819
      ACCOUNTING_STORAGE_HOST: localhost
      ACCOUNTING_STORAGE_PORT: 3306
      COMPUTE_NODES: worker01 worker02
      PARTITION_NAME: docker
      CONTROL_MACHINE: controller.local.dev
      SLURM_USER: slurm
      PASSWORD: test
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=password || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker01:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: espirado/slurm.worker:23.02
    depends_on:
      - controller
    container_name: worker01
    privileged: true
    volumes:
      - ./home:/home
      - ./secret:/.secret
    restart: always
    hostname: worker01.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: controller
      COMPUTE_NODES: worker01 worker02

  worker02:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: espirado/slurm.worker:23.02
    depends_on:
      - controller
    container_name: worker02
    privileged: true
    volumes:
      - ./home:/home
      - ./secret:/.secret
    restart: always
    hostname: worker02.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: controller
      COMPUTE_NODES: worker01 worker02

networks:
  slurm:
