version: '3.1'

services:
  controller:
    image: ghcr.io/ecohealthalliance/slurm_reservoir:controller-gpu
    container_name: controller
    privileged: true
    volumes:
      - ./home:/home
      - ./secret:/.secret
    restart: always
    hostname: controller.local.dev
    networks:
      - slurm
    ports:
      - "22:22"
      - 8080:8787
    environment:
      USE_SLURMDBD: 'true'
      CLUSTER_NAME: megatron
      SLURMCTLD_PORT: 6817
      SLURMD_PORT: 6819
      ACCOUNTING_STORAGE_HOST: localhost
      ACCOUNTING_STORAGE_PORT: 3306
      COMPUTE_NODES: worker01 worker02 worker03 worker04
      PARTITION_NAME: docker
      CONTROL_MACHINE: controller.local.dev
      SLURM_USER: slurm
      PASSWORD: test
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 32G
        reservations:
          cpus: '4'
          memory: 16G

  worker01:
    image: ghcr.io/ecohealthalliance/slurm_reservoir:worker-gpu
    depends_on:
      - controller
    container_name: worker01
    privileged: true
    volumes:
         - ./home:/home
         - ./secret:/.secret
    restart: always
    hostname: worker01.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: controller
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 8G
          

  worker02:
    image: ghcr.io/ecohealthalliance/slurm_reservoir:worker-gpu
    depends_on:
      - controller
    container_name: worker02
    privileged: true
    volumes:
       - ./home:/home
       - ./secret:/.secret
    restart: always
    hostname: worker01.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: controller
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 8G
          

          

networks:
  slurm:
    name: slurm_network

volumes:
  home:
  local:
  shared:
  archive:
  work:
