FROM rocker/geospatial:4.3.0
MAINTAINER "Noam Ross" ross@ecohealthalliance.org

ENV PYTHON_VENV_PATH=/opt/venv/reticulate
RUN /rocker_scripts/install_python.sh

COPY scripts/install_system_tools.sh /reservoir_scripts/install_system_tools.sh
RUN /reservoir_scripts/install_system_tools.sh

COPY scripts/install_eigen_stan_inla.sh /reservoir_scripts/install_eigen_stan_inla.sh
RUN /reservoir_scripts/install_eigen_stan_inla.sh

COPY scripts/install_r_pkgs_compiled.sh /reservoir_scripts/install_r_pkgs_compiled.sh
RUN /reservoir_scripts/install_r_pkgs_compiled.sh

COPY scripts/install_r_pkgs_other.sh /reservoir_scripts/install_r_pkgs_other.sh
RUN /reservoir_scripts/install_r_pkgs_other.sh

COPY scripts/slurm-script.sh /reservoir_scripts/slurm-script.sh
RUN /reservoir_scripts/slurm-script.sh


ADD slurm.conf /etc/slurm-llnl/slurm.conf

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
  && echo $TZ > /etc/timezone \
  && dpkg-reconfigure --frontend noninteractive tzdata

COPY /scripts/server_config.sh /reservoir_scripts/server_config.sh
COPY config /reservoir_config
RUN /reservoir_scripts/server_config.sh

RUN locale-gen en_US.UTF-8

EXPOSE 22 8787
