version: '3.1'

services:
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    image: espirado/slurm.controller:23.02
    container_name: controller
    privileged: true
    volumes:
      - ./home:/home
      - ./secret:/.secret
    restart: always
    hostname: controller.local.dev
    networks:
      - slurm
    environment:
      USE_SLURMDBD: 'true'
      CLUSTER_NAME: snowflake
      SLURMCTLD_PORT: 6817
      SLURMD_PORT: 3306
      ACCOUNTING_STORAGE_HOST: database
      ACCOUNTING_STORAGE_PORT: 3306
      COMPUTE_NODES: worker01 worker02
      PARTITION_NAME: docker
      CONTROL_MACHINE: controller.local.dev

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: espirado/slurm.database:23.02
    depends_on:
      - controller
    container_name: database
    privileged: true
    volumes:
      - ./home:/home
      - ./secret:/.secret
    restart: always
    hostname: database.local.dev
    networks:
      - slurm
    environment:
      DBD_ADDR: database
      DBD_HOST: database
      DBD_PORT: 3306
      STORAGE_HOST: database.local.dev
      STORAGE_PORT: 3306
      STORAGE_PASS: password
      STORAGE_USER: slurm
      CONTROL_MACHINE: controller.local.dev

  worker01:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: espirado/slurm.worker:23.02
    depends_on:
      - controller
    container_name: worker01
    privileged: true
    volumes:
      - ./home:/home
      - ./secret:/.secret
    restart: always
    hostname: worker01.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: database
      COMPUTE_NODES: worker01 worker02

  worker02:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: espirado/slurm.worker:23.02
    depends_on:
      - controller
    container_name: worker02
    privileged: true
    volumes:
      - ./home:/home
      - ./secret:/.secret
    restart: always
    hostname: worker02.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller.local.dev
      ACCOUNTING_STORAGE_HOST: database
      COMPUTE_NODES: worker01 worker02

networks:
  slurm:
