version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: slurm-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=espirado
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
