name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'Controller/Dockerfile.gpu'
      - 'worker/Dockerfile.gpu'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [controller, worker]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push GPU Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.node }}
          file: ./${{ matrix.node }}/Dockerfile.gpu
          push: true
          tags: ghcr.io/ecohealthalliance/slurm-containerized-hpc-environment:${{ matrix.node }}-gpu
          cache-from: type=registry,ref=ghcr.io/ecohealthalliance/slurm-containerized-hpc-environment:${{ matrix.node }}-gpu
